create table movies (
  id bigint generated by default as identity primary key,
  name text,
  description text
);

-- Enable Row Level Security
alter table movies enable row level security;

-- Allow only authenticated users to select rows
create policy "Allow authenticated select" on movies
  for select
  using (auth.role() = 'authenticated');

-- Allow only authenticated users to insert rows
create policy "Allow authenticated insert" on movies
  for insert
  with check (auth.role() = 'authenticated');

-- Allow only authenticated users to update rows
create policy "Allow authenticated update" on movies
  for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Allow only authenticated users to delete rows
create policy "Allow authenticated delete" on movies
  for delete
  using (auth.role() = 'authenticated');